require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'
# use_frameworks! <--- Use frameworks seems to be broken with the current toolchain

target 'UnitTests' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'UnitTestsTests' do
    inherit! :complete
    # Pods for testing
    pod 'OCMock', '3.6'
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  # use_flipper!
  # post_install do |installer|
  #   flipper_post_install(installer)
  # end
end

target 'UnitTests-tvOS' do
  # Pods for UnitTests-tvOS

  target 'UnitTests-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'OCMock', '3.6'
  end
end
